name: Review
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - 'src/assets/**'
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Review PR
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        npm ci
        bash bin/github-review.sh ${{ github.event.number }}
